import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const builtins = builtinModules;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
This plugin reads/writes XMind (.xmind) mind maps inside Obsidian.
*/
;(function () {
  // Mobile (Android/iOS) Obsidian has no Node 'process' global.
  // Provide a minimal shim so bundled deps (JSZip -> lie/immediate)
  // take their browser branches instead of calling process.nextTick/emit.
  if (typeof process === "undefined") {
    globalThis.process = {
      browser: true,
      env: { NODE_ENV: "production" },
      version: "",
      nextTick: function (cb) { return Promise.resolve().then(cb); },
      emit: function () {},
      on: function () {},
      once: function () {},
      removeListener: function () {},
      removeAllListeners: function () {},
    };
  }
})();
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", ...builtins],
  format: "cjs",
  platform: "browser",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
